"""Internal schemas for LLM candidate generation."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class LLMConfig(BaseModel):
    """Configuration for the LLM service."""

    model_config = ConfigDict(extra="forbid")

    api_key: str | None = None
    base_url: str | None = None
    model: str | None = None
    timeout_seconds: int = Field(default=25, ge=1, le=120)
    temperature: float = Field(default=0.7, ge=0.0, le=2.0)
    candidate_count: int = Field(default=12, ge=8, le=30)
    max_tokens: int = Field(default=3000, ge=256, le=16000)
    json_mode: bool = False
    reasoning_effort: Literal["low", "medium", "high"] | None = None


class LLMCandidate(BaseModel):
    """A single knowledge candidate generated by the LLM."""

    model_config = ConfigDict(extra="forbid")

    label: str = Field(min_length=1, max_length=80)
    domain: str = Field(min_length=1, max_length=40)
    description: str = Field(min_length=1, max_length=400)
    connection: str = Field(min_length=1, max_length=400)
    relevance: float = Field(ge=0.0, le=1.0)
    novelty: float = Field(ge=0.0, le=1.0)
    cross_domain: float = Field(ge=0.0, le=1.0)

    @field_validator("label", "domain", "description", "connection", mode="before")
    @classmethod
    def strip_text_fields(cls, value: object) -> object:
        if isinstance(value, str):
            return value.strip()
        return value


class LLMCandidateResponse(BaseModel):
    """Parsed LLM response containing candidate knowledge directions."""

    model_config = ConfigDict(extra="forbid")

    candidates: list[LLMCandidate] = Field(min_length=8, max_length=30)
